<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dama.doctrine.dbal.connection_factory.inner' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/ConnectionFactory.php';

return $this->privates['dama.doctrine.dbal.connection_factory.inner'] = new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory(array());
