<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Utils\MomentFormatConverter' shared autowired service.

include_once $this->targetDirs[3].'/src/Utils/MomentFormatConverter.php';

return $this->privates['App\Utils\MomentFormatConverter'] = new \App\Utils\MomentFormatConverter();
