<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ILnoMpY' shared service.

return $this->privates['.service_locator.ILnoMpY'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('posts' => function (): \App\Repository\PostRepository {
    return ($this->privates['App\Repository\PostRepository'] ?? $this->load('getPostRepositoryService.php'));
}, 'tags' => function (): \App\Repository\TagRepository {
    return ($this->privates['App\Repository\TagRepository'] ?? $this->load('getTagRepositoryService.php'));
}));
