<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yj1g8Ib' shared service.

return $this->privates['.service_locator.yj1g8Ib'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\Admin\\BlogController::delete' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\Admin\\BlogController::edit' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\Admin\\BlogController::index' => function () {
    return ($this->privates['.service_locator.wZSb1Oi'] ?? $this->load('get_ServiceLocator_WZSb1OiService.php'));
}, 'App\\Controller\\Admin\\BlogController::show' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\BlogController::commentForm' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\BlogController::commentNew' => function () {
    return ($this->privates['.service_locator.KN7fXw8'] ?? $this->load('get_ServiceLocator_KN7fXw8Service.php'));
}, 'App\\Controller\\BlogController::index' => function () {
    return ($this->privates['.service_locator.ILnoMpY'] ?? $this->load('get_ServiceLocator_ILnoMpYService.php'));
}, 'App\\Controller\\BlogController::postShow' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\BlogController::search' => function () {
    return ($this->privates['.service_locator.wZSb1Oi'] ?? $this->load('get_ServiceLocator_WZSb1OiService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.UlhrRhb'] ?? $this->load('get_ServiceLocator_UlhrRhbService.php'));
}, 'App\\Controller\\Admin\\BlogController:delete' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\Admin\\BlogController:edit' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\Admin\\BlogController:index' => function () {
    return ($this->privates['.service_locator.wZSb1Oi'] ?? $this->load('get_ServiceLocator_WZSb1OiService.php'));
}, 'App\\Controller\\Admin\\BlogController:show' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\BlogController:commentForm' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\BlogController:commentNew' => function () {
    return ($this->privates['.service_locator.KN7fXw8'] ?? $this->load('get_ServiceLocator_KN7fXw8Service.php'));
}, 'App\\Controller\\BlogController:index' => function () {
    return ($this->privates['.service_locator.ILnoMpY'] ?? $this->load('get_ServiceLocator_ILnoMpYService.php'));
}, 'App\\Controller\\BlogController:postShow' => function () {
    return ($this->privates['.service_locator.zyiLujO'] ?? $this->load('get_ServiceLocator_ZyiLujOService.php'));
}, 'App\\Controller\\BlogController:search' => function () {
    return ($this->privates['.service_locator.wZSb1Oi'] ?? $this->load('get_ServiceLocator_WZSb1OiService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.UlhrRhb'] ?? $this->load('get_ServiceLocator_UlhrRhbService.php'));
}));
