<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOb2WYO2\srcTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOb2WYO2/srcTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOb2WYO2.legacy');

    return;
}

if (!\class_exists(srcTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOb2WYO2\srcTestDebugProjectContainer::class, srcTestDebugProjectContainer::class, false);
}

return new \ContainerOb2WYO2\srcTestDebugProjectContainer(array(
    'container.build_hash' => 'Ob2WYO2',
    'container.build_id' => '31745333',
    'container.build_time' => 1531619236,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOb2WYO2');
